---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: devspaces
  namespace: devspaces-operator
spec: {}
---
kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  name: devspaces
  namespace: devspaces-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
